
#seqcAbst = function() {
# f = readPNG(system.file("pngs/seqc.png", package="ph525x"))
# grid.raster(f)
#}

prender = function(pref) {
 newf = sub("%%PREF%%", pref, "pngs/%%PREF%%.png")
 f = readPNG(system.file(newf, package="ph525x"))
# if (!(dev.cur()==1)) dev.off()
 grid.raster(f)
}

seqcAbst = function() prender("seqc")
seqcDesign = function() prender("seqcFreeH")
obesTitle = function() prender("obesTitle")
obesManh = function() prender("obesManh")
esetDet1 = function() prender("esetFreeH")
esetDet2 = function() prender("esetDet2")
sydhTop = function() prender("SYDHenc")
summex = function() prender("summex")
ggshot = function() prender("ggshot")
firehose = function() prender("firehose")
nastitle = function() prender("nastitle")
stodden1 = function() prender("stodden1")
stodden2 = function() prender("stodden2")
kataegis = function() prender("kataegis")
CRANtop = function() prender("CRANtop")
bcSupp = function() prender("bcSupp")
biocTaskViews = function() prender("biocTaskViews")
biocTop = function() prender("biocTop")
buildRep = function() prender("buildRep")
packLanding = function() prender("packLanding")
scworkflow = function() prender("scworkflow")
taskViews = function() prender("taskViews")
ucscORMDL3 = function() prender("ucscORMDL3")
vignetteAcc = function() prender("vignetteAcc")
wikiCentralDogma = function() prender("wikiCentralDogma")
workflows = function() prender("workflows")
metadb  = function() prender("metadb")
boosStefRP  = function() prender("boosStefRP")
johnson1  = function() prender("johnson1")
johnson2  = function() prender("johnson2")
